### PR TITLE
Updating GPG key server; sks-keyservers.net is offline permanently

### PR DESCRIPTION
**Pull request by kg333**

### CODE REVIEW

**Comment by ProjectMoon** [comment]
I have noticed that the tini installation instructions (AKA the stuff you copy and paste into the dockerfile) tend to change often. Is this keyserver issue the motivation for their latest change? I had to update the tini installation code for a separate project recently.

In order to merge this, I need to fix the master branch. There's a pile of "stuff not building" issues due to how dependencies have been updated (the GraphQL client, specifically) in the past months. I guess this is the motivation for doing so.

**Comment by kg333** [comment]
I can't speak to the tini installation instructions; I just noted it couldn't find the server and found the following discussion that sks-keyservers were now offline: https://www.spinics.net/lists/trinity-devel/msg01400.html

I took a look at the graphql-client-web deprecation, but that's beyond my very limited familiarity with Rust.  The Docker image does build if the last master commit is reverted though.

**Comment by ProjectMoon** [comment]
Here is the plan:

* I will revert the current HEAD of the master branch, because I don't have the time right now to fix the GraphQL client implementation in the web UI.
* The revert-of-the-revert will go back onto a pull request on https://git.agnos.is so I can fix it properly.
* I will merge this, and builds should resume.

**Comment by ProjectMoon** [comment]
The PR is merged. Gitea refuses to open a PR for my revert-of-revert, but that's another issue.

**Pull request merged**
